version = 1

test_patterns = ["tests/*.py"]

exclude_patterns = ["setup.py"]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["pyproject.toml", "setup.py"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 88
  skip_doc_coverage = ["module", "magic", "init"]
  type_checker = "mypy"

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "black"
enabled = true
